AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "AWS SAM Template for zorkinproverserver Lambda with function URL"

Parameters:
  ImageUri:
    Type: String
    Description: "The ECR image URI for the Lambda function"

Resources:
  zorkinproverserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zorkin-prover-server
      Description: ""
      MemorySize: 10240
      Timeout: 900
      Architectures:
        - arm64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Image
      ImageUri: !Ref ImageUri
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/zorkin-prover-server:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None

  zorkinproverserverFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt zorkinproverserver.Arn
      AuthType: NONE
      Cors:
        AllowMethods: [ 'GET', 'POST', 'PUT', 'DELETE', 'PATCH' ]
        AllowOrigins: [ '*' ]
        AllowHeaders:
          - 'Content-Type'
          - 'Authorization'
          - 'X-Amz-Date'
          - 'X-Api-Key'
          - 'X-Amz-Security-Token'
          - 'X-Amz-User-Agent'

Outputs:
  ZorkinProverServerFunctionUrl:
    Description: "URL for the zorkinproverserver Lambda function"
    Value: !GetAtt zorkinproverserverFunctionUrl.FunctionUrl
