# Server configuration
server:
  host: "localhost"
  port: 8002
# Config options for prover
prover:
  circuitsBasePath: "circuits"
  useRapidsnark: false
  rapidsnarkPath: "./build/prove"
log:
  level: "debug"
