# Server configuration
server:
  host: "localhost"
  port: 8002
# Config options for prover
prover:
  circuitsBasePath: "circuits"
  useRapidsnark: true
  rapidsnarkPath: "rapidsnark"
log:
  level: "debug"
